version: "3.8"

services:
  nextjs-app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    stdin_open: true     # Keep container open for dev server
    tty: true            # Allocate a TTY for hot reload/dev mode
    environment:
      - NODE_ENV=development

  email-scheduler-service:
    platform: linux/amd64
    build:
      context: ./email-scheduler-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./email-scheduler-service/.env
    volumes:
      - ./email-scheduler-service:/app
    environment:
      - NODE_ENV=development
